apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: "crossplane/provider-kubernetes:main"
  controllerConfigRef:
    name: kubernetes-controller-config